project:
  type: book
  output-dir: docs

book:
  title: "Lapo + Csenge"
  author: "Csenge Petak"
  date: "2024"
  chapters:
    - index.qmd
    - location.qmd

from: markdown+emoji

format:
  html:
    theme: 
    - cosmo
    - color.scss



