project:
  type: website
  output-dir: docs

website:
  title: "Lapo + Csenge"
  navbar:
    background: transparent
    left:
      - text: Home
        href: index.qmd
      - text: Location
        href: location.qmd
      - text: Info
        href: info.qmd

from: markdown+emoji

format:
  html:
    theme: 
    - cosmo
    - color.scss



