project:
  type: website
  output-dir: docs

website:
  title: "Csenge + Lapo"
  navbar:
    background: transparent

from: markdown+emoji

format:
  html:
    theme: 
    - cosmo
    - color.scss



